### ISSUE TITLE
doesnt work on dedicated server

### ISSUE THREAD

**Issue by phit** [TehStoneMan/BetterStorageToo#27]
snip
```
[22:01:22] [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
>.... [22:01:22] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
BetterStorageToo (betterstorage) has failed to load correctly
§7Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}
```

BetterStorageToo-1.14.4-4.1.0.1

**Comment by TehStoneMan** [comment]
Should now be fixed and available for download.
