### ISSUE TITLE
[1.10.2] Error when trying to break reinforced chest (Gold)

### ISSUE THREAD

**Issue by wise-io** [TehStoneMan/BetterStorageToo#8]
I get this error on our server while trying to break a gold reinforced chest.

`[16:00:04] [Server thread/FATAL]: Error executing task[16:00:04] [Server thread/FATAL]: Error executing taskjava.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151] at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151] at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft at io.github.tehstoneman.betterstorage.utils.WorldUtils.rayTrace(WorldUtils.java:190) ~[WorldUtils.class:?] at io.github.tehstoneman.betterstorage.common.block.BlockLockable.func_180649_a(BlockLockable.java:171) ~[BlockLockable.class:?] at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:196) ~[lv.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:631) ~[me.class:?] at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?] at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?] at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151] at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151] at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?] ... 5 more`

**Comment by TehStoneMan** [comment]
Should be fixed now.
